################################################################################################################
# Site settings                                                                                             #
################################################################################################################
remote_theme: hydecorp/hydejack@v9.0.5

################################################################################################################
# General settings                                                                                             #
################################################################################################################

lang: pt-BR
title: Magento 2 Professional Developer Study Guide
short_title: Magento 2 Professional Developer
description: Minhas anotações de estudo para a certificação “Adobe Certified Professional Magento Commerce Developer (AD0-E702)”.
tagline: Minhas anotações de estudo para a certificação “Adobe Certified Professional Magento Commerce Developer (AD0-E702)”.
keywords: [
  'Magento',
  'Magento 2',
  'certificação',
  'Adobe',
  'e-commerce',
  'developer'
  ]
  
author:
  # Used by `jekyll-feed`:
  name: Ligia Salzano
  email: ligiasalzano@gmail.com
  # # Used by `jekyll-seo-tag`:
  twitter: ligiasalzano
  github: ligiasalzano
  telegram: ligiasalzano
  instagram: ligiasalzano
  linkedin: ligiasalzano

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  
# Add links to the sidebar
menu:
  - title: 01 - Arquitetura magento e técnicas de customização
    url:   /arquitetura-e-customizacao
  - title: 02 - Processamento do fluxo de requisição
    url:   /processamento-do-fluxo-de-requisicao
  - title: 03 - Personalizando a Interface de Usuário (UI) do Magento
    url:   /personalizando-a-ui
  - title: 04 - Trabalhando com banco de dados no Magento
    url:   /trabalhando-com-banco-de-dados
  - title: 05 - Desenvolvendo com o adminhtml
    url:   /desenvolvendo-com-o-adminhtml
  - title: 06 - Personalização da lógica de negócios do Magento
    url:   /personalizacao-da-logica-de-negocios


no_search: false

