remote_theme: hydecorp/hydejack@v9.0.5
menu:
  - title: 01 - Arquitetura magento e técnicas de customização
    url:   01-Arquitetura-e-Customizacao.md
  - title: 02 - Processamento do fluxo de requisição
    url:   02-Fluxo-de-Requisicao.md
  - title: 03 - Personalizando a Interface de Usuário (UI) do Magento
    url:   03-Personalizando-a-UI.md
  - title: 04 - Trabalhando com banco de dados no Magento
    url:   04-Trabalhando-com-banco-de-dados.md
  - title: 05 - Desenvolvendo com o adminhtml
    url:   05-Desenvolvendo-com-o-Adminhtml.md
  - title: 06 - Personalização da lógica de negócios do Magento
    url:   06-Personalizacao-da-Logica-de-Negocios.md
